name: Flarum Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: js/package-lock.json

      # Our action will install npm, cd into `./js`, run `npm run build` and
      # `npm run build-typings`, then commit and upload any changes
      - name: Build production JS
        uses: flarum/action-build@2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: build
          package_manager: npm
          typings_script: build-typings
